### PR TITLE
Remove /etc/linode on package removal

### PR DESCRIPTION
**Pull request by RobertDeRose**

### CODE REVIEW

**Comment by jamesottinger** [comment]
👍

**Comment by jamesottinger** [comment]
Thanks @RobertDeRose!

**Comment by dwfreed** [comment]
I'm late on this (was traveling yesterday), but 👎 .  Packages do not own /etc/<anything>, and therefore should not blindly remove it on uninstallation.  What if the user is storing their Manager API keys in /etc/linode for their own use?  You just blew them away, and now they have to make new ones (or have had them saved elsewhere).  Mark the Longview config files as config files to the package manager, and let the package manager handle cleaning them up when the user requests removal of the package's config files upon removal of the package.

**Comment by RobertDeRose** [comment]
@dwfreed Hrmm... Well I thought about making it just rm -rf /etc/linode/longview.* but from the manual installation of longview client we tell customers to make /etc/linode, so I assumed this was safe, however your point about just telling the package manager about them being config files does make sense, I'll make a new PR.

**Comment by RobertDeRose** [comment]
@dwfreed So, just did a little research, at least for Debian, this would not work. Debian requires that the files actually exist in the package https://www.debian.org/doc/debian-policy/ap-pkg-conffiles.html.

Since all the files in /etc/linode/longview.d and longview.key are created via post-instsll scripts, this wouldn't work.

I would be glad to change the code to `rm -rf /etc/linode/longview.*` instead.  Good compromise?

**Comment by dwfreed** [comment]
Not really, no.  The best option here is to just leave them as is, then.  The user may want to keep them for whatever reason, and just deleting them wholesale is not a great idea.  If a user cares, they can delete them themselves; it's just a couple files and directories.

**Pull request merged**
